[package]
name = "coursepointer"
version = "0.1.0"
edition = "2024"
default-run = "coursepointer"

[lib]
name = "coursepointer"
path = "src/lib.rs"
doctest = false  # Fails on doc comments in private mods

[[bin]]
name = "coursepointer"
path = "src/bin/cli.rs"
required-features = ["cli"]

[dependencies]
byteorder = "1.5.0"
chrono = "0.4.41"
num-traits = "0.2.19"
quick-xml = "0.37.5"
thiserror = "2.0.12"
log = "0.4.27"
anyhow = { version = "1.0.98", optional = true }
clap = { version = "4.5.39", optional = true, features = ["derive"] }
env_logger = { version = "0.11.8", optional = true }
cxx = "1.0.158"
approx = "0.5.1"

[dev-dependencies]
anyhow = "1.0.98"
approx = "0.5.1"
csv = "1.3.1"
serde = { version = "1.0.219", features = ["derive"] }

[features]
default = ["cli"]
cli = ["dep:anyhow", "dep:clap", "dep:env_logger"]
full-geolib = []

[build-dependencies]
cxx-build = "1.0.158"
#lto = true

[workspace]
resolver = "2"
members = ["integration-stub"]
