[package]
name = "coursepointer"
version = "0.1.0"
edition = "2024"
default-run = "coursepointer"

[lib]
name = "coursepointer"
path = "src/lib.rs"
doctest = false  # Fails on doc comments in private mods

[[bin]]
name = "coursepointer"
path = "src/bin/cli.rs"
required-features = ["cli"]

[dependencies]
byteorder = "1.5.0"
chrono = "0.4.41"
num-traits = "0.2.19"
quick-xml = "0.37.5"
thiserror = "2.0.12"
anyhow = { version = "1.0.98", optional = true }
clap = { version = "4.5.39", optional = true, features = ["derive"] }
cxx = "1.0.158"
approx = "0.5.1"
dimensioned = { version = "0.8.0", features = ["approx"] }
clap-cargo = { version = "0.15.2", optional = true }
tracing = { version = "0.1.41", features = ["log"] }
tracing-subscriber = { version = "0.3.19", optional = true, features = ["env-filter"] }
tracing-span-tree = "0.1.1"

[dev-dependencies]
anyhow = "1.0.98"
approx = "0.5.1"
csv = "1.3.1"
serde = { version = "1.0.219", features = ["derive"] }

[features]
default = ["cli"]
cli = ["dep:anyhow", "dep:clap", "dep:clap-cargo", "dep:tracing-subscriber"]
full-geolib = []

[build-dependencies]
cxx-build = "1.0.158"

[workspace]
resolver = "2"
members = ["integration-stub"]

[profile.release]
# Uncomment to enable release build profiling, or set
# CARGO_PROFILE_RELEASE_DEBUG to "true" to do this on a temporary basis.
#debug = "line-tables-only"
# Enable link-time optimization: Slower, but smaller binaries.
#lto = true
