[project]
name = "coursepointer"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"

[tool.uv.workspace]
members = ["integration", "devtools"]

[tool.ruff]
exclude = ["geographiclib/**"]
