[project]
name = "coursepointer"
version = "0.3.3-dev"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "ruff>=0.12.1",
]

[tool.uv.workspace]
members = ["integration", "devtools"]

[tool.ruff]
exclude = ["geographiclib/**"]
