name: setup-and-cache
author: mshroyer
description: setup-and-cache
inputs:
  toolchain:
    description: "Rust toolchain version"
    required: true
    type: string
  default_features:
    description: "Whether to use default crate features"
    required: false
    type: boolean
    default: true
  extra_features:
    description: "Additional crate features to use, comma-separated"
    required: false
    type: string
runs:
  using: "composite"
  steps:
    - name: Install verbose tar
      run: |
        cat << 'EOF' > $RUNNER_TEMP/my-tar.sh
        #!/usr/bin/env bash
        exec tar --verbose "$@"
        EOF
        chmod +x $RUNNER_TEMP/my-tar.sh
        echo "$RUNNER_TEMP" >> $GITHUB_PATH
      shell: bash

    - uses: actions/cache@v4
      with:
        path: |
          ~/.cache/
          ~/.cargo/
          ~/.rustup/toolchains
          ~/.rustup/update-hashes
          ~/.rustup/settings.toml
          .venv/
          target/
        key: build_test-${{ inputs.toolchain }}-${{ runner.os }}-${{ inputs.default_features }}-${{ inputs.extra_features }}

    - name: Setup rust
      if: inputs.toolchain != 'stable'  # Runner already comes with the stable toolchain
      run: rustup toolchain install --profile minimal ${{ inputs.toolchain }} && rustup default ${{ inputs.toolchain }}
      shell: bash

    - name: Print rust version
      run: rustc --version
      shell: bash

    - name: Setup python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Setup uv
      uses: astral-sh/setup-uv@v5
