[project]
name = "coursepointer-rs"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "fitdecode>=0.10.0",
    "garmin-fit-sdk>=21.158.0",
]

[dependency-groups]
dev = [
    "pytest>=8.3.5",
]
