[package]
name = "coursepointer-wasm"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
coursepointer = { version = "0.3.1", path = "../..", default-features = false, features = ["wasm"] }
thiserror = "2.0.12"
wasm-bindgen = "0.2.100"
