name: lint
author: mshroyer
description: lint
runs:
  using: "composite"
  steps:
    - name: Add rust components
      run: rustup component add rustfmt
      shell: bash

    - name: rustfmt
      run: cargo fmt --check
      shell: baseh

    - name: Cargo check
      run: cargo check
      shell: bash

    - uses: astral-sh/ruff-action@v3
      with:
        args: "check"

    - uses: astral-sh/ruff-action@v3
      with:
        args: "format --check --diff"
