# Linting for non-web components

name: lint
author: mshroyer
description: lint
runs:
  using: "composite"
  steps:
    - name: Add rust components
      run: rustup component add rustfmt
      shell: bash

    - name: Run lint
      run: scripts/lint.sh
      shell: bash
