name: web
author: mshroyer
description: web
runs:
  using: "composite"
  steps:
    - name: Setup WASM SDKs
      run: |
        scripts/setup_wasm_sdks.sh
        . scripts/activate_wasm_sdks.sh
        
        # Use the node version pinned by emsdk, and save an separate node 
        # installation step.
        echo "$(dirname "$EMSDK_NODE")" >>$GITHUB_PATH
      shell: bash

    - uses: pnpm/action-setup@v4
      with:
        version: 10

    - name: Install PNPM dependencies
      run: |
        cd web
        pnpm install
      shell: bash

    - name: Check JS/TS format
      run: |
        cd web
        pnpm run format:check
      shell: bash

    - name: PNPM build
      run: |
        cd web
        pnpm build
      shell: bash

    - run: scripts/node_tests.sh
      shell: bash

    - name: Show dist files
      run: tree web/dist
      shell: bash
