name: web
author: mshroyer
description: web
runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: 22

    - uses: pnpm/action-setup@v4
      with:
        version: 10

    - run: sudo apt install emscripten
      shell: bash

    - run: cargo install --locked wasm-pack
      shell: bash

    - name: PNPM build
      run: |
        cd web
        pnpm install
        pnpm build
      shell: bash

    - run: scripts/node_tests.sh
      shell: bash
