[package]
name = "geographic"
version = "0.1.0"
edition = "2024"

[dependencies]
coretypes = { version = "0.1.0", path = "../coretypes" }
cxx = "1.0.157"
thiserror = "2.0.12"

[build-dependencies]
cxx-build = "1.0.157"

[dev-dependencies]
anyhow = "1.0.98"
approx = "0.5.1"

[lib]
doctest = false
