name: build-test
on:
  workflow_call:
    inputs:
      os:
        description: "Operating system to run on"
        required: true
        type: string
      toolchain:
        description: "Rust toolchain version"
        required: true
        type: string
      default_features:
        description: "Whether to use default crate features"
        required: false
        type: boolean
        default: true
      extra_features:
        description: "Additional crate features to use, comma-separated"
        required: false
        type: string
      use_minimal_versions:
        description: "Whether to apply MVS dependency version selection"
        required: false
        type: boolean
        default: false
      web:
        description: "Whether to build and test web and WASM artifacts"
        required: false
        type: boolean
        default: false

permissions:
  contents: read

jobs:
  build_and_test:
    runs-on: ${{ inputs.os }}
    timeout-minutes: 25

    env:
      CARGO_DEFAULT_FEATURES: "${{ inputs.default_features }}"
      CARGO_EXTRA_FEATURES: "${{ inputs.extra_features }}"

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: ./.github/actions/setup-and-cache
        with:
          toolchain: ${{ inputs.toolchain }}

      - name: Update to minimal dependency versions
        run: cargo update -Z minimal-versions
        if: ${{ inputs.use_minimal_versions }}

      - run: cargo build --package devtools
      - run: cargo build -F cli
      - run: cargo test -F cli

        # Integration tests need the cli feature.
        #
        # The integration test package will explicitly enable the cli feature
        # for the coursepointer CLI tests anyway, but it would be redundant to
        # run the integration tests here if we're explicitly testing alternative
        # feature combinations without cli.
      - run: uv run --package integration pytest
        if: ${{ inputs.default_features || contains(inputs.extra_features, 'cli') }}

      - uses: ./.github/actions/lint
        if: ${{ inputs.toolchain == 'nightly' }}

      - uses: ./.github/actions/web
        if: ${{ inputs.web }}
