name: build-test
on:
  workflow_call:
    inputs:
      os:
        description: "Operating system to run on"
        required: true
        type: string
      toolchain:
        description: "Rust toolchain version"
        required: true
        type: string
      default_features:
        description: "Whether to use default crate features"
        required: false
        type: boolean
        default: true
      extra_features:
        description: "Additional crate features to use, comma-separated"
        required: false
        type: string

jobs:
  build_and_test:
    runs-on: ${{ inputs.os }}

    env:
      CARGO_DEFAULT_FEATURES: "${{ inputs.default_features }}"
      CARGO_EXTRA_FEATURES: "${{ inputs.extra_features }}"

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: ./.github/actions/setup-and-cache
        with:
          toolchain: ${{ inputs.toolchain }}

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Setup uv
        uses: astral-sh/setup-uv@v5

      - run: cargo build --verbose
      - run: cargo test --verbose

        # Integration tests need the cli feature.
      - run: uv run --package integration pytest
        if: ${{ inputs.default_features || contains(inputs.extra_features, 'cli') }}