name: CI

on:
  push:
  pull_request:
  schedule:
    - cron: "23 1 * * *"

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: Build and test
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            toolchain: stable
          - os: ubuntu-latest
            toolchain: beta
          - os: ubuntu-latest
            toolchain: nightly
          - os: windows-latest
            toolchain: stable
          - os: macos-latest
            toolchain: stable

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup rust
        run: |
          rustup toolchain install --profile minimal -c rustfmt,clippy ${{ matrix.toolchain }} && \
          rustup default ${{ matrix.toolchain }}

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - run: git submodule update --init
      - run: cargo build --verbose
      - run: cargo test --verbose
      - run: uv run --package integration pytest

  build_and_test_features:
    name: Build and test non-default feature sets
    strategy:
      matrix:
        include:
          - features: ""
          - features: "full-geolib"
          - features: "cli"
          - features: "floor"
          - features: "full-geolib,cli"
          - features: "full-geolib,floor"
          - features: "full-geolib,cli,floor"

    runs-on: ubuntu-latest

    # Integration tests need the `cli` feature and some of their test cases may
    # be painfully slow without the `floor` feature, so here we just make sure
    # it builds and the Rust tests work.
    steps:
      - uses: actions/checkout@v4
      - name: Setup rust
        run: rustup update stable && rustup default stable
      - run: git submodule update --init
      - run: cargo test --no-default-features -F "${{ matrix.features }}" --verbose
