name: Cargo Build and Test

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: Build and test
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            toolchain: stable
          - os: ubuntu-latest
            toolchain: beta
          - os: ubuntu-latest
            toolchain: nightly
          - os: windows-latest
            toolchain: stable
          - os: macos-latest
            toolchain: stable
            
    runs-on: ${{ matrix.os }}
    
    steps:
      - uses: actions/checkout@v4
        
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Setup python
        run: uv python install
      - name: Setup rust
        run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
        
      - run: git submodule update --init
      - run: cargo build --verbose
      - run: cargo test --verbose
      - run: uv run --package integration pytest

  build_and_test_features:
    name: Build and test feature combinations
    strategy:
      matrix:
        include:
          - features: ""
          - features: "full-geolib"
          - features: "cli"
          - features: "floor"
          - features: "full-geolib,cli"
          - features: "full-geolib,floor"
          - features: "cli,floor"
          - features: "full-geolib,cli,floor"

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup rust
        run: rustup update stable && rustup default stable
      - run: git submodule update --init
      - run: cargo test --no-default-features -F "${{ matrix.features }}" --verbose