name: CI

on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "**"
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build_test:
    name: Build and test
    strategy:
      matrix:
        include:
          - os: windows-2025
            toolchain: stable
          - os: macos-latest
            toolchain: stable

    uses: ./.github/workflows/build-test.yml
    with:
      os: ${{ matrix.os }}
      toolchain: ${{ matrix.toolchain }}

  # Make nightly a separate job so we can await it from the lint job without
  # also having to wait for the longer-running Windows build to complete.
  build_test_nightly:
    name: Build and test
    uses: ./.github/workflows/build-test.yml
    with:
      os: ubuntu-latest
      toolchain: nightly

  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: build_test_nightly  # Reuse cache
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: ./.github/actions/setup-and-cache
        with:
          toolchain: nightly

      - name: Add rust components
        run: rustup component add rustfmt

      - name: rustfmt
        run: cargo fmt --check

      - name: Cargo check
        run: cargo check

      - uses: astral-sh/ruff-action@v3
        with:
          args: "check"

      - uses: astral-sh/ruff-action@v3
        with:
          args: "format --check --diff"
