name: CI

on:
  workflow_call:
  push:
    branches:
      - "**"
    tags-ignore:
      - "**"
  pull_request:

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: read

# We can keep overall resource usage low by just testing on ubuntu with nightly.  That way we can
jobs:
  build_test_lint:
    uses: ./.github/workflows/build-test.yml
    with:
      os: ubuntu-latest
      toolchain: nightly
      web: true
