name: Cargo Build and Test

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test_ubuntu:
    name: Build and test on Ubuntu
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
    steps:
      - uses: actions/checkout@v4
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - run: git submodule update --init
      - run: cargo build --verbose
      - run: cargo test --verbose

  build_and_test_windows:
    name: Build and test on Windows (stable)
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup update stable && rustup default stable
      - run: git submodule update --init
      - run: cargo build --verbose
      - run: cargo test --verbose

  build_and_test_macos:
    name: Build and test on macOS (stable)
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup update stable && rustup default stable
      - run: git submodule update --init
      - run: cargo build --verbose
      - run: cargo test --verbose
