name: Cargo Build and Test

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test_ubuntu:
    name: Build and test on Ubuntu
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            toolchain: stable
          - os: ubuntu-latest
            toolchain: beta
          - os: ubuntu-latest
            toolchain: nightly
          - os: windows-latest
            toolchain: stable
          - os: macos-latest
            toolchain: stable
            
    runs-on: ${{ matrix.os }}
    
    steps:
      - uses: actions/checkout@v4
        
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Setup python
        run: uv python install
      - name: Setup rust
        run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
        
      - run: git submodule update --init
      - run: cargo build --verbose
      - run: cargo test --verbose
      - run: uv run --package integration pytest
