name: CI

on:
  push:
  pull_request:
  schedule:
    - cron: "23 1 * * *"

env:
  CARGO_TERM_COLOR: always

jobs:
  build_test:
    name: Build and test
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            toolchain: stable
          - os: ubuntu-latest
            toolchain: beta
          - os: ubuntu-latest
            toolchain: nightly
          - os: windows-2025
            toolchain: stable
          - os: macos-latest
            toolchain: stable

    uses: ./.github/workflows/build-test.yml
    with:
      os: ${{ matrix.os }}
      toolchain: ${{ matrix.toolchain }}

  features:
    name: Test non-default feature sets
    strategy:
      matrix:
        include:
          - features: ""
          - features: "rayon"
          - features: "full-geolib"
          - features: "cli"

    uses: ./.github/workflows/build-test.yml
    with:
      os: ${{ matrix.os }}
      toolchain: ${{ matrix.toolchain }}
      default_features: false
      extra_features: ${{ matrix.features }}

  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: build_and_test  # Reuse cache
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

#      - uses: actions/cache@v4
#        with:
#          path: |
#            ~/.cache/
#            ~/.cargo/
#            ~/.rustup/
#            .venv/
#            target/
#          key: build_and_test_old-nightly-${{ runner.os }}

      - name: Setup rust
        run: rustup toolchain install --profile minimal -c rustfmt nightly && rustup default nightly

      - name: rustfmt
        run: cargo fmt --check

      - name: Cargo check
        run: cargo check

      - uses: astral-sh/ruff-action@v3
        with:
          args: "check"

      - uses: astral-sh/ruff-action@v3
        with:
          args: "format --check --diff"
