name: CI

on:
  workflow_call:
  push:
    branches:
      - "**"
    tags-ignore:
      - "**"
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build_test:
    name: Build and test
    strategy:
      matrix:
        include:
          - os: ubuntu
            toolchain: nightly
          - os: windows-2025
            toolchain: stable
          - os: macos-latest
            toolchain: stable

    uses: ./.github/workflows/build-test.yml
    with:
      os: ${{ matrix.os }}
      toolchain: ${{ matrix.toolchain }}
