name: CI

on:
  push:
  pull_request:
  schedule:
    - cron: "23 1 * * *"

env:
  CARGO_TERM_COLOR: always

jobs:
  build_test:
    name: Build and test
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            toolchain: beta
          - os: windows-2025
            toolchain: stable
          - os: macos-latest
            toolchain: stable

    uses: ./.github/workflows/build-test.yml
    with:
      os: ${{ matrix.os }}
      toolchain: ${{ matrix.toolchain }}

  # Make nightly a separate job so we can await it from the lint job.
  build_test_nightly:
    name: Build and test
    uses: ./.github/workflows/build-test.yml
    with:
      os: ubuntu-latest
      toolchain: nightly

  # Likewise with stable, for the doc job.
  build_test_stable:
    name: Build and test
    uses: ./.github/workflows/build-test.yml
    with:
      os: ubuntu-latest
      toolchain: stable

  features:
    name: Test non-default feature sets
    strategy:
      matrix:
        include:
          - features: ""
          - features: "rayon"
          - features: "full-geolib"
          - features: "cli"

    uses: ./.github/workflows/build-test.yml
    with:
      os: ${{ matrix.os }}
      toolchain: stable
      default_features: false
      extra_features: ${{ matrix.features }}

  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: build_test_nightly  # Reuse cache
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: ./.github/actions/setup-and-cache
        with:
          toolchain: nightly

      - name: Add rust components
        run: rustup component add rustfmt

      - name: rustfmt
        run: cargo fmt --check

      - name: Cargo check
        run: cargo check

      - uses: astral-sh/ruff-action@v3
        with:
          args: "check"

      - uses: astral-sh/ruff-action@v3
        with:
          args: "format --check --diff"

  doc:
    name: Doc
    runs-on: ubuntu-latest
    needs: build_test_stable  # Reuse cache
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: ./.github/actions/setup-and-cache
        with:
          toolchain: nightly

      - name: Build docs
        run: cargo doc
