name: delete-caches
on:
  workflow_dispatch:
  schedule:
    - cron: "23 2 * * 1"

permissions:
  actions: write

jobs:
  delete_caches:
    name: Delete caches
    runs-on: ubuntu-latest

    steps:
      - name: Delete caches
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh cache delete --all --repo mshroyer/coursepointer
