name: Extra Checks
on:
  workflow_call:

jobs:
  build_test:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            toolchain: beta
          - os: ubuntu-latest
            toolchain: nightly
          - os: windows-2025
            toolchain: stable
          - os: macos-latest
            toolchain: stable

    uses: ./.github/workflows/build-test.yml
    with:
      os: ${{ matrix.os }}
      toolchain: ${{ matrix.toolchain }}

  do_features:
    name: Test non-default feature sets
    strategy:
      matrix:
        include:
          - features: ""
          - features: "rayon"
          - features: "full-geolib"
          - features: "cli"

    uses: ./.github/workflows/build-test.yml
    with:
      os: ubuntu-latest
      toolchain: stable
      default_features: false
      extra_features: ${{ matrix.features }}

  doc:
    runs-on: ubuntu-latest
    needs: build_test  # Reuse cache
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: ./.github/actions/setup-and-cache
        with:
          toolchain: stable

      - name: Build docs
        run: cargo doc
