name: publish-website
on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Build website
        uses: ./.github/actions/web

      - name: Configure AWS OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::466456532355:role/github-coursepointer.app-s3-upload
          aws-region: us-east-1
          role-session-name: github-${{ github.run_id }}

      - name: Publish to S3
        run: |
          scripts/publish_web.sh
