name: release
on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"
    branches-ignore:
      - "**"

permissions:
  actions: read
  contents: write

jobs:
  create_release:
    name: Create release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Wait for successful CI run
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python3 scripts/release.py wait-ci ${{ github.sha }}

      - name: Install cargo-about
        run: cargo install --locked cargo-about

      - name: Lint release
        run: python3 scripts/release.py lint

      - name: Create draft release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python3 scripts/release.py create

  macos_binary:
    name: Build and upload macOS binary
    runs-on: macos-latest
    needs: create_release

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install x86_64 target
        run: rustup target add x86_64-apple-darwin

      - name: Build and upload artifacts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: scripts/upload_macos.sh

  windows_binary:
    name: Build and upload Windows binary
    runs-on: windows-2025
    needs: create_release

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Build and upload artifacts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: scripts/upload_windows.ps1
