name: release
on:
  workflow_dispatch:

permissions:
  actions: read

jobs:
  check_release:
    name: Check whether ready for release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Check for successful CI run
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python3 scripts/check_ci_run.py ${{ github.sha }}

      - name: Check release
        run: python3 scripts/check_release.py

      - name: Generate release notes
        run: python3 scripts/gen_release_notes.py
