name: release
on:
  workflow_dispatch:

permissions:
  actions: read

jobs:
  check_release:
    name: Check whether ready for release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/github-script@v7
        id: check-ci
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const runs = await github.rest.checks.listForRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: context.sha
            });
            const ciRun = runs.data.check_runs.find(c => c.name === 'CI');
            if (!ciRun) {
              core.setFailed('No CI check found on this ref');
            } else if (ciRun.status !== 'completed') {
              core.setFailed(`CI status is still ${ciRun.status}`);
            } else if (ciRun.conclusion !== 'success') {
              core.setFailed(`CI concluded with ${ciRun.conclusion}`);
            }

      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup uv
        uses: astral-sh/setup-uv@v5

      - name: Check release
        run: uv run tools/check_release.py
