name: release
on:
  workflow_dispatch:

permissions:
  actions: read

jobs:
  check_release:
    name: Check whether ready for release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Check for successful CI run
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: scripts/check_ci_run.py ${{ github.sha }}

      - name: Setup uv
        uses: astral-sh/setup-uv@v5

      - name: Check release
        run: uv run tools/check_release.py
